### ISSUE TITLE
libopencv_java3.so "Missing rule"

### ISSUE THREAD

**Issue by techievbv** [dbeqiraj/Akaze#2]
Hi, 
Hope you are good.
I followed the exact steps you mentioned in the project, but unfortunately I'm unable to build the project with the following error:
Error:error: '../../../../src/main/jniLibs/arm64-v8a/libopencv_java3.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it.

I'm unable to understand the cause for this error. Any ideas /suggestions are welcome.

**Comment by dbeqiraj** [comment]
I just tried it and I couldn't generate the error. 
Make sure to do **exactly** what I describe in the steps. Use version  3.3.0 for OpenCV. Make sure that **jniLibs** folder has this hierarchy: _/main/jniLibs/(arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64)_. And cppThirdParty folder this hierarchy: _main/cppThirdParty/include/(opencv, opencv2..)_.

Close and open the project.

**Comment by techievbv** [comment]
@dbeqiraj I'm using OpenCV version 3.4.1 . Is that to be blamed for the error ?

**Comment by dbeqiraj** [comment]
Maybe but, I have not tried it.
